#
# ChargeSigns Configuration
#
# Do NOT Change This
ConfigVer: 1
General:
  ## NOT IMPLEMENTED Should ChargeSigns tell you if a newer version is available?
  InformOnUpdates: false
  ## NOT IMPLEMENTED Should ChargeSigns give you extra information in the Console?
  DebugMode: false
  ## NOT IMPLMENTED Should ChargeSigns refund a player for breaking the sing?
  RefundOnBreak: false
Charge:
  Lockette:
      Private: true
        Cost: 4
        Refund: 2
      MoreUsers: true
        Cost: 2
        Refund: 1
        
 