#
# ChargeSigns Configuration
#
General:
  ## Do NOT Change ConfigVersion
  ConfigVersion: 1
  ## Not yet Implemented
  Language: en
Signs:
  Test1:
    Cost: 1
  Test2:
    Cost: 2
  Test22:
    Cost: 23
  Chuck:
    Cost: 5