#
# ChargeSigns Configuration
#
General:
  ## Do NOT Change ConfigVersion
  ConfigVersion: 1
  ## Not yet Implemented
  Language: en
Signs:
  ##Here are Some Examples, if a Sign Contains "Test1" on any line the player will be charged $1
  test1:
    Cost: 1
  ## if a Sign Contains [Private] on any line, the player will be charged $2
  "[private]":
    Cost: 2
  test22:
    Cost: 23
  chuck:
    Cost: 5
  "[urlsigns]":
    Cost: 10
  ## These are just Examples, you can add as many as you want!  make sure to use spaces
  ## Instead of tabs.  If you're going to us Brackets [ ] put quotes around them "[Example]"
  ## Don't use Capital Letters for Sign Text.  always use lowercase (Example:  Instead or [URLSigns] use [urlsigns]