name: ChargeSigns
main: io.github.tda0909.ChargeSigns.ChargeSigns
depend: [Vault]
version: Beta v1.28
description: Charge Players to Place Certain Signs as Defined in the config.yml
author: tda0909
website: http://dev.bukkit.org/bukkit-plugins/chargesigns/
commands:
  chargesigns:
    description: Plug-in Test
    aliases: [cs, chargeS, sCharge]
    usage: /<command>
    permission-message: You don't have <permission>
permissions:
  chargesigns.*:
    description: Grants Full Command Access
    default: op
  chargesigns.reload:
    description: Reloads Config
    default: op
  chargesigns.exempt:
    description: Doesn't Charge Player to Place Signs
    default: op
  chargesigns.version:
    description: Gets Plug-In Version
    default: op
  chargesigns.modify:
    description: Add, Remove, & Change Costs Via Commands
    default: op
  chargesigns.cost:
    description: Use Command to See Cost
    default: true
  chargesigns.norefund:
    description: Will not Give Player Refund
    default: false