name: ChargeSigns
main: io.github.tda0909.ChargeSigns.ChargeSigns
depend: [Vault]
version: Beta v1.2
description: Developmental Plug-in
author: tda0909
website: http://dev.bukkit.org/bukkit-plugins/chargesigns/
commands:
  chargesigns:
    description: Plug-in Test
    aliases: [cs, chargeS, sCharge]
    usage: /<command>
    permission-message: You don't have <permission>
permissions:
  changesigns.*:
    description: Grants Full Command Access
    default: op
  changesigns.reload:
    description: Reloads Config
    default: op
  changesigns.exempt:
    description: Doesn't Charge Player to Place Signs
    default: op
  changesigns.version:
    description: Gets Plug-In Version
    default: op
  changesigns.modify:
    description: Add, Remove, & Change Costs Via Commands
    default: op
  changesigns.cost:
    description: Use Command to See Cost
    default: true
  changesigns.norefund:
    description: Will not Give Player Refund
    default: false